################################################################################
#
# fastfetch
#
################################################################################

FASTFETCH_VERSION = 2.67.1
FASTFETCH_SITE = $(call github,fastfetch-cli,fastfetch,$(FASTFETCH_VERSION))
FASTFETCH_LICENSE = MIT
FASTFETCH_LICENSE_FILES = LICENSE
FASTFETCH_DEPENDENCIES = host-pkgconf

# Keep X11/XCB/Xrandr (for resolution/GPU on the 600X); drop all heavy/tangential.
FASTFETCH_CONF_OPTS = \
	-DENABLE_X11=ON -DENABLE_XCB=ON -DENABLE_XRANDR=ON -DENABLE_XCB_RANDR=ON \
	-DENABLE_VULKAN=OFF -DENABLE_WAYLAND=OFF -DENABLE_DRM=OFF -DENABLE_VADRM=OFF \
	-DENABLE_VAX11=OFF -DENABLE_VDPAU=OFF -DENABLE_GIO=OFF -DENABLE_DCONF=OFF \
	-DENABLE_EET=OFF -DENABLE_DBUS=OFF -DENABLE_SQLITE3=OFF -DENABLE_RPM=OFF \
	-DENABLE_IMAGEMAGICK7=OFF -DENABLE_IMAGEMAGICK6=OFF -DENABLE_CHAFA=OFF \
	-DENABLE_EGL=OFF -DENABLE_GLX=OFF -DENABLE_OPENCL=OFF -DENABLE_FREETYPE=OFF \
	-DENABLE_PULSE=OFF -DENABLE_DDCUTIL=OFF -DENABLE_ELF=OFF -DENABLE_ZLIB=OFF \
	-DENABLE_LUA=OFF -DENABLE_QUICKJS=OFF -DENABLE_LIBZFS=OFF -DENABLE_WCWIDTH=OFF \
	-DENABLE_THREADS=OFF -DBUILD_FLASHFETCH=OFF -DBUILD_TESTS=OFF

$(eval $(cmake-package))